export const LOAD_FACILITIES_SUCCESS = "LOAD_FACILITIES_SUCCESS";
export const BEGIN_FACILITIES_API_CALL = "BEGIN_FACILITIES_API_CALL";
export const LOAD_MONITORING_PLANS_SUCCESS = "LOAD_MONITORING_PLANS_SUCCESS";
export const BEGIN_MONITORING_PLANS_API_CALL =
  "BEGIN_MONITORING_PLANS_API_CALL";
export const LOAD_MONITORING_METHODS_SUCCESS =
  "LOAD_MONITORING_METHODS_SUCCESS";
export const BEGIN_MONITORING_METHODS_API_CALL =
  "BEGIN_MONITORING_METHODS_API_CALL";
export const LOAD_MONITORING_MATSMETHODS_SUCCESS =
  "LOAD_MONITORING_MATSMETHODS_SUCCESS";
export const BEGIN_MONITORING_MATSMETHODS_API_CALL =
  "BEGIN_MONITORING_MATSMETHODS_API_CALL";
export const ADD_FACILITY_TAB = "ADD_FACILITY_TAB";
export const REMOVE_FACILITY_TAB = "REMOVE_FACILITY_TAB";
export const LOAD_MONITORING_SYSTEMS_SUCCESS =
  "LOAD_MONITORING_SYSTEMS_SUCCESS";
export const BEGIN_MONITORING_SYSTEMS_API_CALL =
  "BEGIN_MONITORING_SYSTEMS_API_CALL";
