export const LOAD_FACILITIES_SUCCESS = "LOAD_FACILITIES_SUCCESS";
export const BEGIN_FACILITIES_API_CALL = "BEGIN_FACILITIES_API_CALL";
export const LOAD_MONITORING_PLANS_SUCCESS = "LOAD_MONITORING_PLANS_SUCCESS";
export const BEGIN_MONITORING_PLANS_API_CALL =
  "BEGIN_MONITORING_PLANS_API_CALL";
