export default {
  facilities: [],
  monitoringPlans: [],
  apiCallsInProgress: {
    facilities: false,
    monitoringPlans: false,
    monitoringMethods: false,
    monitoringSystems: false,
    monitoringMatsMethods: false,
    monitoringSystemsComponents: false,
  },
  openedFacilityTabs: {
    monitoringPlans: [],
    qaCertTestSummary: [],
    export: [],

    emissionsDaily: [],
    emissionsHourly: [],
    emissionsMats: [],
    emissions:[]
  },
  dropdowns: {
    defaults: [],
    formulas: [],
    loads: [],
    locationAttributesAndRelationships: [],
    methods: [],
    qualifications: [],
    lmeQualifications: [],
    leeQualifications: [],
    pctQualifications: [],
    rectangularDuctWafs: [],
    spans: [],
    systems: [],
    unitFuels: [],
    unitControls: [],
    unitCapacities: [],
    fuelFlows: [],
    systemComponents: [],
    analyzerRanges: [],
    matsMethods: [],
  },
  currentSection: "",
};
