export default {
  facilities: [],
  monitoringPlans: [],
  apiCallsInProgress: {
    facilities: false,
    monitoringPlans: false,
    monitoringMethods: false,
    monitoringSystems: false,
    monitoringMatsMethods: false,
    monitoringSystemsComponents: false,
  },
  openedFacilityTabs: [],
  activeTab: [0],
  dropdowns: {
    defaults: [],
    formulas: [],
    loads: [],
    locationAttributes: [],
    locationRelationships: [],
    methods: [],
    qualifications: [],
    lmeQualifications: [],
    leeQualifications: [],
    pctQualifications: [],
    rectangularDuctWafs: [],
    spans: [],
    systems: [],
    unitFuels: [],
    unitControls: [],
    unitCapacities: [],
    fuelFlows: [],
    systemComponents: [],
    analyzerRanges: [],
    matsMethods: [],
  },
  currentSection: "",
};
