#!/bin/bash

echo "$1: GITHUB_RUN_NUMBER"
echo "$2: GITHUB_WORKSPACE"
echo "$3: GITHUB_REPOSITORY"

echo "$GITHUB_RUN_NUMBER : GITHUB_RUN_NUMBER"
echo "$GITHUB_WORKSPACE : GITHUB_WORKSPACE"
echo "$GITHUB_REPOSITORY : GITHUB_REPOSITORY"
