CREATE OR REPLACE VIEW camddmw.vw_hour_unit_data
 AS
 SELECT uf.state,
    uf.facility_name,
    uf.orispl_code,
    uf.unit_id,
    uf.unitid,
    uf.assoc_stacks,
    hud.op_date,
    hud.op_hour,
    hud.op_time,
    hud.op_year,
    hud.gload,
    hud.sload,
    hud.so2_mass,
    hud.so2_mass_measure_flg,
    hud.so2_rate,
    hud.so2_rate_measure_flg,
    hud.co2_mass,
    hud.co2_mass_measure_flg,
    hud.co2_rate,
    hud.co2_rate_measure_flg,
    hud.nox_mass,
    hud.nox_mass_measure_flg,
    hud.nox_rate,
    hud.nox_rate_measure_flg,
    hud.heat_input,
    hud.heat_input_measure_flg,
    uf.primary_fuel_info,
    uf.secondary_fuel_info,
    uf.unit_type_info,
    uf.so2_control_info,
    uf.nox_control_info,
    uf.part_control_info,
    uf.hg_control_info,
    uf.prg_code_info
   FROM camddmw.hour_unit_data hud
     JOIN camddmw.unit_fact uf ON hud.unit_id = uf.unit_id AND hud.op_year = uf.op_year
     JOIN camddmw.op_year oy ON hud.op_year = oy.op_year AND oy.archive_ind = 0::numeric
UNION ALL
 SELECT uf.state,
    uf.facility_name,
    uf.orispl_code,
    uf.unit_id,
    uf.unitid,
    uf.assoc_stacks,
    hud.op_date,
    hud.op_hour,
    hud.op_time,
    hud.op_year,
    hud.gload,
    hud.sload,
    hud.so2_mass,
    hud.so2_mass_measure_flg,
    hud.so2_rate,
    hud.so2_rate_measure_flg,
    hud.co2_mass,
    hud.co2_mass_measure_flg,
    hud.co2_rate,
    hud.co2_rate_measure_flg,
    hud.nox_mass,
    hud.nox_mass_measure_flg,
    hud.nox_rate,
    hud.nox_rate_measure_flg,
    hud.heat_input,
    hud.heat_input_measure_flg,
    uf.primary_fuel_info,
    uf.secondary_fuel_info,
    uf.unit_type_info,
    uf.so2_control_info,
    uf.nox_control_info,
    uf.part_control_info,
    uf.hg_control_info,
    uf.prg_code_info
   FROM camddmw_arch.hour_unit_data_a hud
     JOIN camddmw.unit_fact uf ON hud.unit_id = uf.unit_id AND hud.op_year = uf.op_year
     JOIN camddmw.op_year oy ON hud.op_year = oy.op_year AND oy.archive_ind = 1::numeric;