#!/bin/bash

cf set-env $APP_NAME REACT_APP_EASEY_ECMPS_UI_API_KEY $ECMPS_API_KEY
cf set-env $APP_NAME REACT_APP_EASEY_ECMPS_UI_CLIENT_ID $ECMPS_CLIENT_ID
cf set-env $APP_NAME REACT_APP_EASEY_ECMPS_UI_CLIENT_SECRET $ECMPS_CLIENT_SECRET
