--SET DATABASE
\c cgawsbrokerprodg1t1yiwikl6s1rs

CREATE SCHEMA "CAMDECMPSMD" AUTHORIZATION uwoha4melpr2pzxq;

CREATE TABLE "CAMDECMPSMD"."CONTROL_CODE" (
  "CONTROL_CD" VARCHAR(7) NOT NULL,
	"CONTROL_DESCRIPTION" VARCHAR(1000) NOT NULL,
	"CONTROL_EQUIP_PARAM_CD" VARCHAR(7),
	CONSTRAINT "PK_CONTROL_CODE" PRIMARY KEY ("CONTROL_CD"),
	CONSTRAINT "UQ_CONTROL_DESC" UNIQUE ("CONTROL_DESCRIPTION")
);
COMMENT ON COLUMN "CAMDECMPSMD"."CONTROL_CODE"."CONTROL_CD" IS 'Codes for identifying type of control equipment.';
COMMENT ON COLUMN "CAMDECMPSMD"."CONTROL_CODE"."CONTROL_DESCRIPTION" IS 'Description of control equipment codes.';
COMMENT ON COLUMN "CAMDECMPSMD"."CONTROL_CODE"."CONTROL_EQUIP_PARAM_CD" IS 'Identifies control type.';
COMMENT ON TABLE "CAMDECMPSMD"."CONTROL_CODE"  IS 'Lookup table of control types.';

CREATE TABLE "CAMDECMPSMD"."FUEL_INDICATOR_CODE" (
  "FUEL_INDICATOR_CD" VARCHAR(7) NOT NULL,
	"FUEL_INDICATOR_DESCRIPTION" VARCHAR(1000) NOT NULL,
	CONSTRAINT "PK_FUEL_INDICATOR_CODE" PRIMARY KEY ("FUEL_INDICATOR_CD"),
	CONSTRAINT "UQ_FUEL_INDICATOR_CODE_DESC" UNIQUE ("FUEL_INDICATOR_DESCRIPTION")
);
COMMENT ON COLUMN "CAMDECMPSMD"."FUEL_INDICATOR_CODE"."FUEL_INDICATOR_CD" IS 'Unique code for the fuel indicator.';
COMMENT ON COLUMN "CAMDECMPSMD"."FUEL_INDICATOR_CODE"."FUEL_INDICATOR_DESCRIPTION" IS 'Full description of the indicator code.';
COMMENT ON TABLE "CAMDECMPSMD"."FUEL_INDICATOR_CODE"  IS 'Lookup table containing the fuel indicator codes.';

CREATE TABLE "CAMDECMPSMD"."FUEL_TYPE_CODE" (
  "FUEL_TYPE_CD" VARCHAR(7) NOT NULL,
	"FUEL_TYPE_DESCRIPTION" VARCHAR(1000) NOT NULL,
	"FUEL_GROUP_CD" VARCHAR(7),
	CONSTRAINT "PK_FUEL_TYPE_CODE" PRIMARY KEY ("FUEL_TYPE_CD"),
	CONSTRAINT "UQ_FUEL_TYPE_CODE_DESC" UNIQUE ("FUEL_TYPE_DESCRIPTION")
);
COMMENT ON COLUMN "CAMDECMPSMD"."FUEL_TYPE_CODE"."FUEL_TYPE_CD" IS 'The type of fuel which a UNIT is capable or will be capable of combusting.';
COMMENT ON COLUMN "CAMDECMPSMD"."FUEL_TYPE_CODE"."FUEL_TYPE_DESCRIPTION" IS 'Full description of fuel type.';
COMMENT ON COLUMN "CAMDECMPSMD"."FUEL_TYPE_CODE"."FUEL_GROUP_CD" IS 'Identifies the category of fuel (e.g., gas, oil or other).';
COMMENT ON TABLE "CAMDECMPSMD"."FUEL_TYPE_CODE"  IS 'Lookup table containing codes for the fuels used by units.';

CREATE TABLE "CAMDECMPSMD"."REPORTING_PERIOD" (
  "RPT_PERIOD_ID" NUMERIC(38,0) NOT NULL,
	"CALENDAR_YEAR" NUMERIC(38,0) NOT NULL,
	"QUARTER" NUMERIC(38,0) NOT NULL,
	"BEGIN_DATE" DATE NOT NULL,
	"END_DATE" DATE NOT NULL,
	"PERIOD_DESCRIPTION" VARCHAR(100) NOT NULL,
	"PERIOD_ABBREVIATION" VARCHAR(32) NOT NULL,
	"ARCHIVE_IND" NUMERIC(1,0) DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_REPORTING_PERIOD" PRIMARY KEY ("RPT_PERIOD_ID"),
	CONSTRAINT "UQ_CALENDAR_YR_QTR" UNIQUE ("CALENDAR_YEAR", "QUARTER")
);
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."RPT_PERIOD_ID" IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."CALENDAR_YEAR" IS 'Reporting Year. ';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."QUARTER" IS 'Reporting Quarter. ';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."BEGIN_DATE" IS 'The begin date of the reporting period.';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."END_DATE" IS 'The end date of the reporting period.';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."PERIOD_DESCRIPTION" IS 'The description of the reporting period.';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."PERIOD_ABBREVIATION" IS 'The abbreviated description of the reporting period.';
COMMENT ON COLUMN "CAMDECMPSMD"."REPORTING_PERIOD"."ARCHIVE_IND" IS 'Used to indicate whether the reporting period has been archived.';
COMMENT ON TABLE "CAMDECMPSMD"."REPORTING_PERIOD"  IS 'Lookup table for reporting periods.';
