--SET DATABASE
\c cgawsbrokerprodg1t1yiwikl6s1rs

CREATE SCHEMA "CAMDECMPS" AUTHORIZATION uwoha4melpr2pzxq;

CREATE TABLE "CAMDECMPS"."MONITOR_PLAN" (
  "MON_PLAN_ID" VARCHAR(45) NOT NULL,
	"FAC_ID" NUMERIC(38,0) NOT NULL,
	"CONFIG_TYPE_CD" VARCHAR(7),
	"LAST_UPDATED" DATE,
	"UPDATED_STATUS_FLG" VARCHAR(1),
	"NEEDS_EVAL_FLG" VARCHAR(1),
	"CHK_SESSION_ID" VARCHAR(45),
	"USERID" VARCHAR(8),
	"ADD_DATE" DATE DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_DATE" DATE,
	"SUBMISSION_ID" NUMERIC(38,0),
	"SUBMISSION_AVAILABILITY_CD" VARCHAR(7),
	"BEGIN_RPT_PERIOD_ID" NUMERIC(38,0) NOT NULL,
	"END_RPT_PERIOD_ID" NUMERIC(38,0),
	CONSTRAINT "PK_MONITOR_PLAN" PRIMARY KEY ("MON_PLAN_ID") DEFERRABLE
);
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."MON_PLAN_ID" IS 'Unique identifier of a monitoring plan record. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."FAC_ID" IS 'Unique identifier of a facility record which is generated by the EPA Host System. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."CONFIG_TYPE_CD" IS 'Code used to identify the configuration type ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."LAST_UPDATED" IS 'Date and time in which either one of the flags was last triggered. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."UPDATED_STATUS_FLG" IS 'If set to true, identifies that changes have been made to the monitoring plan from within the client tool, consequently data must be submitted to the Host. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."NEEDS_EVAL_FLG" IS 'Identifies whether the data need to have checks run against it. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."CHK_SESSION_ID" IS 'Identifies the most recent check session used for the evaluation. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."USERID" IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."ADD_DATE" IS 'Date and time in which record was added. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."UPDATE_DATE" IS 'Date and time in which record was last updated. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."SUBMISSION_ID" IS 'Unique identifier of a submission.';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."SUBMISSION_AVAILABILITY_CD" IS 'Unique code value for a lookup table.';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."BEGIN_RPT_PERIOD_ID" IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN "CAMDECMPS"."MONITOR_PLAN"."END_RPT_PERIOD_ID" IS 'Unique identifier of a reporting period record. ';
COMMENT ON TABLE "CAMDECMPS"."MONITOR_PLAN"  IS 'Table of monitoring plan(s) created by the user.';

CREATE TABLE "CAMDECMPS"."UNIT_CAPACITY" (
  "UNIT_CAP_ID" VARCHAR(45) NOT NULL,
	"UNIT_ID" NUMERIC(38,0) NOT NULL,
	"BEGIN_DATE" DATE,
	"END_DATE" DATE,
	"MAX_HI_CAPACITY" NUMERIC(7,1),
	"USERID" VARCHAR(8) NOT NULL,
	"ADD_DATE" DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"UPDATE_DATE" DATE,
	CONSTRAINT "PK_UNIT_CAPACITY" PRIMARY KEY ("UNIT_CAP_ID")
);
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."UNIT_CAP_ID" IS 'Identity key for UNIT_CAPACITY table.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."UNIT_ID" IS 'Identity key for UNIT table.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."BEGIN_DATE" IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."END_DATE" IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."MAX_HI_CAPACITY" IS 'The maximum hourly heat input (mmBtu/hr) associated with a UNIT.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."USERID" IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."ADD_DATE" IS 'Date the record was created.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CAPACITY"."UPDATE_DATE" IS 'Date of the last record update.';
COMMENT ON TABLE "CAMDECMPS"."UNIT_CAPACITY"  IS 'Identifies historical unit capacity for a unit id.';

CREATE TABLE "CAMDECMPS"."UNIT_CONTROL" (
  "CTL_ID" VARCHAR(45) NOT NULL,
	"UNIT_ID" NUMERIC(38,0) NOT NULL,
	"CONTROL_CD" VARCHAR(7) NOT NULL,
	"CE_PARAM" VARCHAR(7) NOT NULL,
	"INSTALL_DATE" DATE,
	"OPT_DATE" DATE,
	"ORIG_CD" VARCHAR(1),
	"SEAS_CD" VARCHAR(1),
	"RETIRE_DATE" DATE,
	"INDICATOR_CD" VARCHAR(7),
	"USERID" VARCHAR(8) NOT NULL,
	"ADD_DATE" DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"UPDATE_DATE" DATE,
	CONSTRAINT "PK_UNIT_CONTROL" PRIMARY KEY ("CTL_ID")
);
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."CTL_ID" IS 'Unique identifier of a unit control record.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."UNIT_ID" IS 'Unique identifier of a unit record.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."CONTROL_CD" IS 'Codes used to identify the type of control equipment.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."CE_PARAM" IS 'Code used to identify the parameter which is controlled by the control equipment.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."INSTALL_DATE" IS 'Approximate date the original control equipment was or will be installed.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."OPT_DATE" IS 'The approximate date on which optimization of control equipment was completed and the equipment made fully operational if the control equipment was not part of the original installation.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."ORIG_CD" IS 'Code used to identify that the control equipment was installed and operational as part of the original unit design.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."SEAS_CD" IS 'Code used to identify if the NOx control equipment was used during the ozone season.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."RETIRE_DATE" IS 'Date control equipment was retired.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."INDICATOR_CD" IS 'Code used to identify the fuel or control type.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."USERID" IS 'User account or source of data that added or updated record.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."ADD_DATE" IS 'Date and time in which record was added.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_CONTROL"."UPDATE_DATE" IS 'Date and time in which record was last updated.';
COMMENT ON TABLE "CAMDECMPS"."UNIT_CONTROL"  IS 'Control equipment planned to be used or is used to reduce emissions at a unit.';

CREATE TABLE "CAMDECMPS"."UNIT_FUEL" (
  "UF_ID" VARCHAR(45) NOT NULL,
	"UNIT_ID" NUMERIC(38,0) NOT NULL,
	"FUEL_TYPE" VARCHAR(7) NOT NULL,
	"BEGIN_DATE" DATE NOT NULL,
	"END_DATE" DATE,
	"INDICATOR_CD" VARCHAR(7),
	"ACT_OR_PROJ_CD" VARCHAR(7),
	"OZONE_SEAS_IND" NUMERIC(1,0),
	"DEM_SO2" VARCHAR(7),
	"DEM_GCV" VARCHAR(7),
	"SULFUR_CONTENT" NUMERIC(5,4),
	"USERID" VARCHAR(8) NOT NULL,
	"ADD_DATE" DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"UPDATE_DATE" DATE,
	CONSTRAINT "PK_UNIT_FUEL" PRIMARY KEY ("UF_ID"),
	CONSTRAINT "UQ_UNIT_FUEL" UNIQUE ("UNIT_ID", "FUEL_TYPE", "BEGIN_DATE"),
	CONSTRAINT "CK_ACT_OR_PROJ_CD" CHECK ("ACT_OR_PROJ_CD" IN ('A','P',NULL))
);
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."UF_ID" IS 'Identity key for UNIT_FUEL table.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."UNIT_ID" IS 'Identity key for UNIT table.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."FUEL_TYPE" IS 'The type of fuel which a UNIT is capable or will be capable of combusting.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."BEGIN_DATE" IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."END_DATE" IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."INDICATOR_CD" IS 'Code that indicates fuel or control type.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."ACT_OR_PROJ_CD" IS 'Indicator of whether the begin date for the fuel type is an actual date or a projected date.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."OZONE_SEAS_IND" IS 'Indicator that FUEL is used during ozone season.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."DEM_SO2" IS 'Demonstration method to qualify for daily fuel sampling for percent sulfur.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."DEM_GCV" IS 'Demonstration method to qualify for monthly GCV fuel sampling.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."SULFUR_CONTENT" IS 'The percent sulfur content of the fuel, by weight.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."USERID" IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."ADD_DATE" IS 'Date the record was created.';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_FUEL"."UPDATE_DATE" IS 'Date of the last record update.';
COMMENT ON TABLE "CAMDECMPS"."UNIT_FUEL"  IS 'Identifies the actual or projected fuel type a UNIT is capable of combusting at a specified time.';

CREATE TABLE "CAMDECMPS"."UNIT_STACK_CONFIGURATION" (
  "CONFIG_ID" VARCHAR(45) NOT NULL,
	"UNIT_ID" NUMERIC(38,0) NOT NULL,
	"STACK_PIPE_ID" VARCHAR(45) NOT NULL,
	"BEGIN_DATE" DATE NOT NULL,
	"END_DATE" DATE,
	"USERID" VARCHAR(8),
	"ADD_DATE" DATE DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_DATE" DATE,
	CONSTRAINT "PK_UNIT_STACK_CONFIGURATION" PRIMARY KEY ("CONFIG_ID")
);
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."CONFIG_ID" IS 'Unique identifier of a monitoring configuration record. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."UNIT_ID" IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."STACK_PIPE_ID" IS 'Unique identifier of a stack or pipe record. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."BEGIN_DATE" IS 'Date in which information became effective or activity started. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."END_DATE" IS 'Last date in which information was effective or date in which activity ended. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."USERID" IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."ADD_DATE" IS 'Date and time in which record was added. ';
COMMENT ON COLUMN "CAMDECMPS"."UNIT_STACK_CONFIGURATION"."UPDATE_DATE" IS 'Date and time in which record was last updated. ';
COMMENT ON TABLE "CAMDECMPS"."UNIT_STACK_CONFIGURATION"  IS 'Identifies the units, stacks or pipes that are associated with a specific monitoring plan.';

