name: ECMPS Automated Tests

on:
  # schedule:
  #   # Runs "At 00:00, only on Friday and Tuesday" (see https://crontab.guru) 
  #   - cron: '0 0 * * 5,2'
  
  workflow_dispatch:
    
jobs:
  Automated-Tests:
    runs-on: ubuntu-latest
   
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Checkout testing repo
      uses: actions/checkout@v3
      with: 
          repository: US-EPA-CAMD/easey-testing
          path: easey-testing

    - name: Build with Maven
      run: |
        cd easey-testing
        mvn clean install

    - name: Run Tests
      run: mvn clean test -Dname=Test_ECMPSUI_SMK_MonPlanPage
    
 
