name: Automated Tests-CRON

on:
  schedule:
    # Runs "At 00:00, only on Friday and Tuesday" (see https://crontab.guru) 
    - cron: '0 0 * * 5,2'

jobs:
  Automated-Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout testing repo
      uses: actions/checkout@v3
      with: 
          repository: US-EPA-CAMD/easey-testing
          path: easey-testing
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn test
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # - name: Run
      #   run: mvn clean test -Dname=Test_ECMPSUI_SMK_MonPlanPage
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
